name: practice
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Update apt-get
      run: sudo apt-get update

    - name: Install Kerberos
      run: sudo apt-get install -y krb5-user

    - name: Install AWS collection
      run: ansible-galaxy collection install amazon.aws

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Add any other dependencies you need to install here

    - name: Install Terraform
      run: |
        sudo apt-get install -y gnupg software-properties-common curl
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get update && sudo apt-get install -y terraform

    - name: Print working directory
      id: print_working_dir
      run: echo "Working directory is $(pwd)"

    - name: Initialize Terraform
      run: terraform init
      working-directory: ${{ steps.print_working_dir.outputs.working_dir }}

    - name: Apply Terraform
      run: terraform apply -auto-approve
      working-directory: ${{ steps.print_working_dir.outputs.working_dir }}
